---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mesosphere.github.io/charts/staging
      chart: traefik-forward-auth
      version: 0.3.3
      sourceRef:
        kind: HelmRepository
        name: mesosphere-staging-charts
        namespace: flux-system
      interval: 10m

  values:
    traefikForwardAuth:
      clientId: "${AUTH_CLIENT_ID}"
      clientSecret:
        value: "${AUTH_CLIENT_SECRET}"
      authHost: "${AUTH_SERVER}"
      domain: "${SECRET_DOMAIN}"
      oidcUri: "${AUTH_ISSUER}"
          
    ingress:
      enabled: true
      hosts:
        - host: "auth.${SECRET_DOMAIN}"
          paths:
            - /
      tls:
        - secretName: "${SECRET_DOMAIN/./-}-tls"
          hosts:
            - "auth.${SECRET_DOMAIN}"
    middleware:
      enabled: true
      name: bloopy-auth
