---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://jupyterhub.github.io/helm-chart/
      chart: jupyterhub
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: jupyterhub-charts
        namespace: flux-system
      interval: 5m
  values:
    hub:
      db:
        pvc:
          storageClassName: oci-fss
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
      hosts:
      - "jhub.${SECRET_DOMAIN}"
      tls:
      - hosts:
        - "jhub.${SECRET_DOMAIN}"
    singleuser:
      storage:
        extraVolumes:
          - name: jupyterhub-shared
            persistentVolumeClaim:
              claimName: pvc-jupyterhub
        extraVolumeMounts:
          - name: jupyterhub-shared
            mountPath: /home/shared
