---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://jupyterhub.github.io/helm-chart/
      chart: jupyterhub
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: jupyterhub-charts
        namespace: flux-system
      interval: 5m
  values:
    hub:
      db:
        type: postgres
        url: "${JHUB_DB_URL}"
      config:
        Authenticator:
          admin_users:
            - ${JHUB_ADMIN}
        GitHubOAuthenticator:
          client_id: ${GITHUB_AUTH_CLIENT_ID}
          client_secret: ${GITHUB_AUTH_CLIENT_SECRET}
          oauth_callback_url: ${GITHUB_OAUTH_CALLBACK}
        JupyterHub:
          authenticator_class: github
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        hajimari.io/enable: "true"
        hajimari.io/icon: "chart-scatter-plot"
        hajimari.io/appName: "jupyterhub"
      hosts:
      - "jhub.${SECRET_DOMAIN}"
      tls:
      - hosts:
        - "jhub.${SECRET_DOMAIN}"
    singleuser:
      storage:
        static:
          pvcName: pvc-jupyterhub
      # Defines the default image
      image:
        name: jupyter/datascience-notebook
        tag: latest
      profileList:
        - display_name: "Minimal environment"
          description: "To avoid too much bells and whistles: Python."
          kubespawner_override:
            image: jupyter/minimal-notebook:latest
        - display_name: "Datascience environment"
          description: "If you want the additional bells and whistles: Python, R, and Julia."
          default: true
        - display_name: "Spark environment"
          description: "The Jupyter Stacks spark image!"
          kubespawner_override:
            image: jupyter/all-spark-notebook:latest
        - display_name: "Learning Data Science"
          description: "Datascience Environment with Sample Notebooks"
          kubespawner_override:
            image: jupyter/datascience-notebook:latest
            lifecycle_hooks:
              postStart:
                exec:
                  command:
                    - "sh"
                    - "-c"
                    - >
                      gitpuller https://github.com/data-8/materials-fa17 master materials-fa;
