---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://code-server-boilerplates.github.io/charts
      chart: code-server
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: cdr-charts
        namespace: flux-system
      interval: 5m

  dependsOn:
    - name: cert-manager
      namespace: cert-manager

  values:
    image:
      repository: codercom/code-server
      tag: 4.7.1
    extraVars:
      - name: TZ 
        value: ${TZ}
      - name: PASSWORD
        value: ${CODE_SERVER_PASSWORD}
    persistence:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        secret.reloader.stakater.com/reload: "auto"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hajimari.io/enable: "true"
        hajimari.io/appName: "Code Server"
        hajimari.io/icon: "vs-code"
      hosts:
        - host: "ide.${SECRET_DOMAIN}"
          paths:
            - /
      tls:
        - hosts:
            - "ide.${SECRET_DOMAIN}"
    podSecurityContext:
      fsGroup: 101
    resources:
      requests:
        cpu: 100m
        memory: 128M
