---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://code-server-boilerplates.github.io/charts
      chart: code-server
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: cdr-charts
        namespace: flux-system
      interval: 5m

  dependsOn:
    - name: cert-manager
      namespace: cert-manager

  values:
    image:
      repository: codercom/code-server
      tag: v0.1.0
    env:
      TZ: "${TZ}"



    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          secret.reloader.stakater.com/reload: "auto"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # traefik.ingress.kubernetes.io/router.middlewares: "networking-bloopy-auth@kubernetescrd"
          hajimari.io/enable: "true"
          hajimari.io/appName: Dashboard
          hajimari.io/icon: "weather-sunset"
        hosts:
          - host: "${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "${SECRET_DOMAIN}"
    podSecurityContext:
      fsGroup: 101
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    resources:
      requests:
        cpu: 100m
        memory: 128M
