apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-codeserver
 namespace: default
spec:
 storageClassName: oci-fss
 accessModes:
   - ReadWriteMany
 resources:
  requests:
    storage: 500Mi
 volumeName: clarice
