# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    BLOOPNET_URI: ENC[AES256_GCM,data:7HY5rRubr/TSkaYHzqdv,iv:+MMLBUfTRoZbE0IbeN8O0yc/GJy03/HK1xoH60U28XE=,tag:WKoiwAawINXB0duy20gL2A==,type:str]
    SECRET_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:H4snLxU7k2ovfGBBV75Z4E3PzWdAgCOt4lT7q6Ks9072DyYIEel93A==,iv:hPUTgvN38XXPiHoWNiBcBE5Kkyn/FHz2odN5W2RDzVo=,tag:2bCe2ypI/N92nfovBZKcUA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:IX1TCAVA04kyTpzV9Q==,iv:AWCUvJn0qHjPTAKq+lE39kiFu9XMkkqC2qB6ulPBOkU=,tag:V/NMAzujH5/5lCYAafcNdQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:MyJ0mlwW5QnEwpW4szNQy0VO,iv:cSmo1EqhckGvznvx0xpUyace2QDvp/GftUyujL7yE7c=,tag:zQZtE+yhcVBhF8+Zwg2xmw==,type:str]
    SECRET_TRAEFIK_PILOT_TOKEN: ENC[AES256_GCM,data:qXHxs0gaUBVabO3a7wtlIj3EcBSYlGO5l47kMBwQ1osSuQg7,iv:KgnpZ08ILagBszY0NIKKipBJ36K8hx2ravvBGTEFwoY=,tag:nfIoPozyBhADlQIBmpm8xQ==,type:str]
    KEYCLOAK_POSTGRES_USER: ENC[AES256_GCM,data:XHlusdzHNd8=,iv:S8lZ1bcTdRMi24CJ6zfEI83DkGAFLMHJ13ZzGjSqFi0=,tag:2bvNx0Vo1SzJeA9RiJtYzA==,type:str]
    KEYCLOAK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:ZROfxFJWWvLQEpE9hNtdduitIQ==,iv:JReS72qGivHvZ93U+MWXkUk+eOPqBdYMMzE/fURyVP8=,tag:Wd/2VPP0q0KG6iWf7FWqlQ==,type:str]
    KEYCLOAK_POSTGRES_DB: ENC[AES256_GCM,data:rGbRtzUdyfo=,iv:o/yT66yZDx/86YXrIehtw06Khj108VGdIr8QQci3Nhk=,tag:pYiaAszqahvhLW8rVzMapg==,type:str]
    MOUNT_TARGET_ID: ENC[AES256_GCM,data:B7oX77ldkZl9ZFpHYzjmCzJs3m20YrtY3H/qMQ1yakASQZvpTvSlOQVtkn1W2ysQNjVPzDCor+Gp9wlbFGV/AcqgdE/bdRCrsRM=,iv:gRe63dwq+XTrpmLB6i3ay06/PeTd3JG96ur3n/mQDmM=,tag:eE3xVcfwX5NvTF+UM1gjKg==,type:str]
    CLARICE_IP: ENC[AES256_GCM,data:m/6cGyr2MOopTw==,iv:4lB9bsugN1EYMpdWhMqB+OEcHqcdx1TdbCADZ0w97rE=,tag:6j9bWDReWKNotGanu4BJpw==,type:str]
    CLARICE_PATH: ENC[AES256_GCM,data:T3EksoofcMwBRGJda2lp2zLm,iv:AWaE0UzVl7eMO2R+sPQ+lpljDJklEcI4AGrnzKbbWwA=,tag:yd9+2j2I8rVzAhFFO8sWMg==,type:str]
    KEYCLOAK_USER: ENC[AES256_GCM,data:qk9FJJo=,iv:gfM843V+3KctCuB3ByS3BF6oYT5YRKZSkpvwj0WPZC4=,tag:3FBF7VIBgIibg4yKsOxEZg==,type:str]
    KEYCLOAK_PASSWORD: ENC[AES256_GCM,data:fVClwxoWcmiP/8kzHfiD6mFOJw==,iv:pKsjpfjCXbrslUR74VUczdc+rg9TGSVturTvXv9eHsI=,tag:Y1qeyalcofspjwCk2YHqTg==,type:str]
    AUTH_SERVER: ENC[AES256_GCM,data:ZhqjSRvfpnKnVBFh8MmUWf5NkpF2mHGh9PxvON1LdA==,iv:4TqueEKcbXL2L+mT1IG5nL4kzj/8aNjy37diR6tEViQ=,tag:oAVWe9cvrulMh+8xYUKl7Q==,type:str]
    AUTH_CLIENT_ID: ENC[AES256_GCM,data:X0A6Cai2lYLfjLKUh91X1HU=,iv:72ROn88qDyVwzMwfT486NHlNXynzQaXYAcg2YHjL99c=,tag:uWfQ3nkSB9mJC7px+pVQ8w==,type:str]
    AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:hz1i8DPh8e7ia16pc+Nsgb+SHv2uaXWlBX9fNz6nzaLBcU/o,iv:8A5uilNiHY73kCsY2wpC+avAxVECGTz7RSjYkSrIqzg=,tag:kRK0htBeaZW85kp2eKuD9g==,type:str]
    AUTH_ISSUER: ENC[AES256_GCM,data:CE8BZzVml/zWWgS2E2N30yhnw6rqZfbUSU8CJCKiv1j26QjzJ/kurwOzV2I7xQs=,iv:++5iW7Ocm5ktKScCufAKZS7Xy+B/QnCPryyUo/sP034=,tag:CTn3kqOSx1IulOMJeAHNAw==,type:str]
    CODE_SERVER_PASSWORD: ENC[AES256_GCM,data:ms4kAE/GXP4Rfs3K5T9tvnxZfg==,iv:m5J/HRuTMtpyflami8T/vagWnMZBKXJepLfOR71QsPE=,tag:zqnrVKPc/fzlHCNnyvbLRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-11T16:12:06Z"
    mac: ENC[AES256_GCM,data:axSzN9kF3FoPPSPVIoPsDwYd6H2vsg9ar8uJ6dnkgFQN+dhrHUYKAaOv8ndBQlkezl5sCQyvoMZSYjdBVgtLL2gj+k8DjEystwhY1LQY+KGdNY2Bd8qC3IMJkvyKg1mtJKRNPh6jCgmdI+Mh3bDwEPsRmKWXFSntIb42h45JD7U=,iv:2Enb5sZA4YpJPX58nMfBaASJ8WjcNESyRUVrcnAsfJ8=,tag:zDPXZKCpI9jvr0DN1in2Lg==,type:str]
    pgp:
        - created_at: "2021-09-11T16:12:04Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQIMA7o1G9YUCENaARAAlbUduSFGSeAFJr+I8KXr6rMeZxzmzF/yd4+YvdICfU7M\r\num64KbqXlZdA4iOKykhPcwKpC8YB24wsFuinEVcog+xHUSootDiDtlsgI5hUNqFX\r\neOhx8rcFxWKm9bm/9Yvx/C5vkayC5E/qkugn4bl0Sl7KuALWrgJHQOV33z0xHi3j\r\nHsT3vb6CptAkXPL+Nu7ffHg7sXOqkYdXkhA1rZtSuIg72bwkA2osjVp4+8xSBteu\r\nl8fFnWIag5MHud8YBraNAi7SurZP8KPRJAdW6ixhQjrsewXQ/VeJPefsvSDC+its\r\ncDCND7vD8ocPt2nlgMsukWMt3H55gYT0X+QBjFLCMs771pI7phruqym3kS7dyyUD\r\nPx2ppmPC0kJqftRrZK5iWVOY9nf/futGqGZ8++QPZ36ZZziCCRe8/q2GIubuRIHQ\r\nhpqpaQli+7+o6lgBTEkSKaWbnzupx15zA/FShGBwSRprO0lgxtTVafKA0YKHsKOg\r\nf03cPmxSMJ4CplQeQtRs53iq1K32qteQB8ag06nD1nNiWJwa7spEFJ0dbILeiLdN\r\n2o0jnjKXdLZEzAOpB8bX5ps35hJsPZr5U4lsTzg5nsWg2Xe+dg6rs84UizRWtxvA\r\nA6AvlGWEIPp8YsFAHimt7bVDq1nYNYwvkdqkKYgglYnYRA5Sh/+0pqI2VEyhUAXS\r\nXgEXIzT3rGax3oB0hSVUw1EjaaIsQPpSMgS3YLCYZV7F5SyQEqQEcIHnpr+Cg6/X\r\nIj3Q61chf8+m8YKJ+ssboSGwreYAxcUjEO5xweFF2ORm2ay7FS2mzJcWrsluBcg=\r\n=yrrY\r\n-----END PGP MESSAGE-----\r\n"
          fp: C9E9F89A87602182D106AF2C1FEEAA0B0634069C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
