---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 10.24.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 15m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager

  install:
    remediation:
      retries: 4
  upgrade:
    remediation:
      remediateLastFailure: true

  values:
    deployment:
      kind: Deployment
      replicas: 1

    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: "${SVC_TRAEFIK_LB}"
        externalIPs:
          - "${SVC_TRAEFIK_LB}"
        externalTrafficPolicy: Local

    annotations:
      "bloop-env": "test"
      service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
      service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/oci-load-balancer-tls-secret: "${SECRET_DOMAIN/./-}-tls"

    logs:
      general:
        format: json
        level: DEBUG
      access:
        enabled: true
        format: json

    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1

    ingressRoute:
      dashboard:
        enabled: false

    globalArguments:
      - "--api.insecure=true"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"

    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.ip=${SVC_TRAEFIK_LB}"
      - "--providers.kubernetescrd.allowexternalnameservices=true"

    ports:
      traefik:
        expose: true
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        sniStrict: true
    pilot:
      enabled: true
      token: "${SECRET_TRAEFIK_PILOT_TOKEN}"
    experimental:
      plugins:
        enabled: false
        
    resources:
      requests:
        memory: 100Mi
        cpu: 500m
      limits:
        memory: 500Mi
