---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: auth
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://codecentric.github.io/helm-charts
      chart: keycloak
      version: 16.0.5
      sourceRef:
        kind: HelmRepository
        name: codecentric-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: docker.io/jboss/keycloak
      tag: latest
    env:
      TZ: "${TZ}"

    podSecurityContext:
      fsGroup: 1000

    autoscaling:
      enabled: true
      minReplicas: 1

    postgresql:
      enabled: true
      postgresqlUsername: ${KEYCLOAK_POSTGRES_USER}
      postgresqlPassword: ${KEYCLOAK_POSTGRES_PASSWORD}
      postgresqlDatabase: ${KEYCLOAK_POSTGRES_DB}
      networkPolicy:
        enabled: false
      securityContext:
        enabled: true
        fsGroup: 1001
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
      psp:
        create: true
      rbac:
        create: true
      persistence:
        enabled: true
        existingClaim: pvc-postgres
      volumePermissions:
        enabled: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - i386
                      - i686
                      - x86

    extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_USER
        value: ${KEYCLOAK_USER}
      - name: KEYCLOAK_PASSWORD
        value: ${KEYCLOAK_PASSWORD}

    affinity: |
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 60
            preference:
              matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - i386
                    - i686
                    - x86
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hajimari.io/enable: "true"
        hajimari.io/icon: "key-wireless"
        hajimari.io/appName: "keycloak"
      rules:
        - host: "auth.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
          - "auth.${SECRET_DOMAIN}"


