---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: auth
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://codecentric.github.io/helm-charts
      chart: keycloak
      version: 14.0.1
      sourceRef:
        kind: HelmRepository
        name: codecentric-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: docker.io/jboss/keycloak
      tag: latest
    # args: ["--platform=linux/amd64"]
    env:
      TZ: "${TZ}"
    
    podSecurityContext:
      fsGroup: 1000
    
    autoscaling:
      enabled: true

    postgresql:
      enabled: true
      postgresqlUsername: ${KEYCLOAK_POSTGRES_USER}
      postgresqlPassword: ${KEYCLOAK_POSTGRES_PASSWORD}
      postgresqlDatabase: ${KEYCLOAK_POSTGRES_DB}
      networkPolicy:
        enabled: false
      persistence:
        enabled: true
        existingClaim: pvc-postgres
      affinity: 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - i386
                      - i686
                      - x86
    
    extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"

    affinity: |
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - i386
                      - i686
                      - x86
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: traefik-default-middlewares-chain@kubernetescrd
          traefik.ingress.kubernetes.io/router.tls.options: traefik-secure-tlsoptions@kubernetescrd
          hajimari.io/enable: "true"
          hajimari.io/icon: "key-wireless"
          hajimari.io/appName: "traefik"
        hosts:
        - host: "auth.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "auth.${SECRET_DOMAIN}"
    
  
        
