---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: auth
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://codecentric.github.io/helm-charts
      chart: keycloak
      version: 14.0.1
      sourceRef:
        kind: HelmRepository
        name: codecentric-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: docker.io/jboss/keycloak
      tag: latest
    # args: ["--platform=linux/amd64"]
    env:
      TZ: "${TZ}"
    postgresql:
      enabled: false
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: traefik-default-middlewares-chain@kubernetescrd
          traefik.ingress.kubernetes.io/router.tls.options: traefik-secure-tlsoptions@kubernetescrd
          hajimari.io/enable: "true"
          hajimari.io/icon: "key-wireless"
          hajimari.io/appName: "traefik"
        hosts:
        - host: "auth.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "auth.${SECRET_DOMAIN}"
    
  
        
