---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: auth
spec:
  storageClassName: oci
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 35Gi