---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io/
      chart: cert-manager
      version: v1.6.1
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system

  test:
    enable: false # Enable helm test

  install:
    remediation: # perform remediation when helm install fails
      retries: 3

  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true

  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true

  values:
    installCRDs: false

    webhook:
      enabled: true

    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53
      - --dns01-recursive-nameservers-only

    tolerations:
      - key: "arm"
        operator: "Exists"
        
    cainjector:
      replicaCount: 1
      tolerations:
        - key: "arm"
          operator: "Exists"
          
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
        - "1.1.1.1"
        - "8.8.8.8"
        
