---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  
  dependsOn:
    - name: cert-manager
      namespace: cert-manager

  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.1.0
    env:
      TZ: "${TZ}"
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - default
          - networking
          - auth
          - media
      name: "Visitor"
      customApps:
        - name: BloopNet
          url: ${BLOOPNET_URI}
          icon: test-tube
        - name: Plex@Camelus
          url: "https://plex.${BLOOPNET_URI}"
          icon: television-play
        - name: Ombi@Camelus
          url: "https://ombi.${BLOOPNET_URI}"
          icon: tray-plus
        - name: Heimdall
          url: "https://heimdall.${BLOOPNET_URI}"
          icon: book-outline
      groups:
        - name: Communicate
          links:
            - name: Discord
              url: 'https://discord.com'
            - name: Gmail
              url: 'http://gmail.com'
            - name: Slack
              url: 'https://slack.com/signin'
        - name: Cloud
          links:
            - name: Azure
              url: 'https://portal.azure.com'
            - name: Oracle
              url: 'https://console.us-ashburn-1.oraclecloud.com'
            - name: Google Cloud
              url: 'https://console.cloud.google.com/'
        - name: Dev
          links:
            - name: Github
              url: 'https://github.com/h3mmy'
            - name: Gitlab
              url: 'https://gitlab.com/h3mmy'
        - name: Media
          links:
            - name: YouTube
              url: 'https://youtube.com/feed/subscriptions'
            - name: Netflix
              url: 'https://netflix.com/'
        - name: Reading
          links:
            - name: NYTimes
              url: 'http://nytimes.com'
            - name: Reddit
              url: 'http://reddit.com'
        - name: Tech
          links:
            - name: The Verge
              url: 'https://theverge.com/'
            - name: MIT Technology Review
              url: 'https://www.technologyreview.com/'
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          secret.reloader.stakater.com/reload: "auto"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # traefik.ingress.kubernetes.io/router.middlewares: "networking-bloopy-auth@kubernetescrd"
        hosts:
          - host: "${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "${SECRET_DOMAIN}"
    podSecurityContext:
      fsGroup: 101
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    resources:
      requests:
        cpu: 100m
        memory: 128M
